name: 'Build the Unity Runtime'

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build-runtime:
    name: 'Build the Unity Runtime'
    runs-on: ubuntu-latest

    environment: ${{ github.event.pull_request.head.repo.fork == 'true' && 'MR' || 'Production' }}

    env:
      IS_EXTERNAL: ${{ github.event.pull_request.head.repo.fork == 'true' }}

    steps:
      - name: 'Generate a token'
        id: generate-token
        if: ${{ env.IS_EXTERNAL != 'true' }}
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_CLONE_TOKEN_ID }}
          private-key: ${{ secrets.GH_APP_CLONE_TOKEN_SECRET }}
          owner: ${{ github.repository_owner }}
          repositories:
            Renderite.Unity.Renderer.UMP

      - name: 'Mask generated variable'
        if: ${{ env.IS_EXTERNAL != 'true' }}
        shell: bash
        run: echo "::add-mask::${{ steps.generate-token.outputs.token }}"

      - name: 'Check out repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: 'true'
          path: 'UnityRuntime'
          token: ${{ env.IS_EXTERNAL == 'true' && github.token || steps.generate-token.outputs.token }}
          submodules: ${{ github.event_name != 'pull_request' }}

      - name: 'Remove UMP Directory on external PR'
        if: ${{ env.IS_EXTERNAL == 'true' }}
        working-directory: 'UnityRuntime'
        run: rm -rf Assets/UniversalMediaPlayer

      - name: 'Pull Unity from cache'
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: unity-setup-linux-2019.4.19f1-windows-mono
          path: /home/runner/Unity/Hub/Editor

      - name: 'Install Unity'
        continue-on-error: true
        run: |
          curl -sL https://hub.unity3d.com/linux/keys/public | sudo gpg --dearmor -o /usr/share/keyrings/Unity_Technologies_ApS.gpg
          sudo tee /etc/apt/sources.list.d/unity-cli.sources <<'EOF'
          Types: deb
          URIs: https://hub.unity3d.com/linux/repos/deb
          Suites: unstable
          Components: main
          Signed-By: /usr/share/keyrings/Unity_Technologies_ApS.gpg
          EOF

          sudo apt-get update && sudo apt-get install -y unity-cli

          unity editors -i
          unity install 2019.4.19f1 -a x86_64 -m windows-mono --cm

      - name: 'Activate Unity license'
        env:
          UNITY_SERVICE_ACCOUNT_ID: '${{ secrets.UNITY_CI_ACCOUNT_ID }}'
          UNITY_SERVICE_ACCOUNT_SECRET: '${{ secrets.UNITY_CI_ACCOUNT_KEY }}'
        run: unity auth

      - name: 'Build Unity Runtime'
        run: /home/runner/Unity/Hub/Editor/2019.4.19f1/Editor/Unity -quit -batchmode -nographics -projectPath UnityRuntime/ -buildTarget StandaloneWindows64 -executeMethod AppBuilder.BuildWindows
